# Generated by Django 3.2.10 on 2022-06-30 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_product_added_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='added_by',
        ),
    ]
